### ISSUE TITLE
ECP - Provisional Leadership Council

### ISSUE THREAD

**Issue by Dev-JamesR** [Ether1Project/ECPs#1]
**Summary**

A provisional leadership council to work along side the existing Ether-1 team to decide on some immediate project needs, direction and to test and then finalize the rules/protocols needed in order to implement a fully functional decentralized governance system.

**Details**

1. The provisional leadership council should consist of 7 community members, contributors and team members and will be mainly responsible for refining and voting on proposals put forth by the existing Ether-1 leadership team.

2. A secondary responsibility will be to determine where any funds should be spent/used.

3. Any community member, contributor or team member should be eligible to run for a provisional council seat simply by nominating themselves and publishing their ideas/directions they want the project to head in.

4. The provisional council would be elected by the overall Ether-1 community. 

5. Once elected/organized, a simple council voting majority should be used to pass/fail any proposal put forth for consideration.

6. The Ether-1 leadership team should have the ability to check/balance any delegated responsibilities during this provisional period.

7. Provisional council will remain in place until a permanent governance constitution is voted in and a permanent council is elected. 

8. The Ether-1 leadership team will not be eligible to run for this provisional council.

**Comment by fallengravity** [comment]
I’m 100% happy with this setup, it’s a good foundation for the full governance platform.

**Comment by hashratez** [comment]
Is it possible to add an "expected implementation timeline"?

**Comment by fallengravity** [comment]
Sure, We'd like to commence voting within 5-7 days and have the results by the 30th of November, This way the Provisional Council can begin working from the 1st of December.

**Comment by Dev-JamesR** [comment]
For provisional elections we will be creating a git repo specifically for council nominations and platforms so anyone who would like to run for council may do so by posting their public nomination in the provisional governance repo.

**Comment by hashratez** [comment]
What are we going to use for the election mechanics, a ETH SC or something as simple as a Discord Poll (at least for the beginning)???

**Comment by Dev-JamesR** [comment]
The provisional election will be highly simplified and likely a simple pole to get things moving fast. Permanent governance elections will be built into the chain via contract and other methods

**Comment by Primate411** [comment]
> Is it possible to add an "expected implementation timeline"?

**Comment by Primate411** [comment]
We are starting the provisional council ahead of time because it's necessary to discuss many details about Ether-1's future and decide on some changes along with coming up with a "community roadmap" for the near term future. No better way to make these decisions than with the help of trusted community members, elected by the community.

**Comment by Primate411** [comment]
I'm not eligible to run for council but if I was eligible, I would do so like this:

1. I will decide on what I want for the future of Ether-1 based on my deeply held beliefs about crypto in the future
2. I will summarize these beliefs into a cogent platform (a short description of beliefs) with a link to a longer version (not required but highly recommended) and post it in the provisional council repo here [Ether-1 Governance](https://github.com/Ether1Project/Governance/issues)
3. Include your name, Discord username and user ID, and some additional ways to get ahold of you in case of an emergency (Discord/Telegram/Email/Twitter/etc., the more ways the better)

For example...

----

**Contact info**
(Discord) `@Primate of $ETHO since Oct'18#1111 ` ID: <393479955956367370> 
(Email) corporateprimate@gmail.com

**Ether-1 Community History**
Hi I'm Primate411 and I'd like to run for Ether-1 council because I've been following the project for more than a year.

**Platform Summary**
- Change rewards to benefit node holders
- Rebrand project to attract more people
- I want to run the Ether-1 store

**Platform Details**
I think we need to change the rewards in order to give more to our node owners. I've observed that miners dump their ETHO right away and I think with PirlGuard in place we don't have to worry about the chain as much. ETH 2.0 should allow Ether-1 to adopt a PoS model which will further help with blockchain security. Rewarding node holders allows us to get more nodes on the network to help grow ethoFS and node owners don't dump like miners.
I also think we need to explore how much it would cost to rebrand the project in order to attract the people who're currently offput by the name which is too similar to Ethereum.  We should pay respects to where we came from by always mentioning that the project is an Ethereum clone but we need our own unique identity in order to truly thrive.  The project is much more than a simple ETH clone now that the Decentralize Node Protocol is in testing, which pays nodes without a centralized payment processor like 99% of the other masternode coins out there.
Finally, I believe I will be the best person to help run the Ether-1 store and help onboard other people into the store.  I will come up with a plan for this venture and present it to the council for approval.

---

Put your platform forward now over at [](https://github.com/Ether1Project/Governance/issues)

**Comment by Goose-Tech** [comment]
**Contact Info**
(Discord) °☆ Goose [UTC -4]#5820
(e-mail) goose@goosetech.pro

**Ether-1 Community History**
I have been following Ether-1 for over 1 year now. I have a small YouTube channel focused on technology and cryptocurrency where I have made several videos in support of the Ether-1 vision and the project's goal of providing webhosting through the use of smart contracts and IPFS storage. At a time when censorship is becoming an almost constant threat, I believe that a decentralized solution such as IPFS will help pave the path to a free sharing of information and ideas, which is what the internet has been designed to do.

**Platform Summary**
- Bring awareness to the project by promoting the Ether-1 project on YouTube and other social media outlets
- Assist the Ether-1 team in realizing the goal to #DecentralizeEverything
- Find altruistic ways in which the technology being built may give people a means to freely share their ideas

**Platform Details**
One of the challenges any upstart faces is getting others excited about what they are doing. The Ether-1 team has done a phenomenal job of not only forking a highly popular cryptocurrency (Ethereum), but has improved upon it to give it added significance. Smart contracts are one of the most significant innovations in the blockchain space besides Bitcoin; to put smart contracts to use as the backbone for websites takes hosting to a whole other level of autonomy. In the future, there will be no need for centralized webhosting providers. All users will have to do is get some ETHO and host their own content on a fully decentralized IPFS storage network made possible by smart contracts. 

While IPFS storage is the most decentralized solution for websites and sharing content, there are drawbacks, e.g. uploaded files cannot be changed or modified, so mistakes or updates will be difficult to manage. There are no tools to help users develop their own website, or templates to give them the ability to more easily create a site and upload it to ethoFS. Also, the network currently has a limited amount of space, and the fee to upload is cost prohibitive for large files (such as videos). We need solutions to these problems.

At this stage in project development I would propose the following:
1a. A re-evaluation of the block reward fee to incentivize node owners more than miners (this will encourage more people to create nodes, which will help mitigate a lack of storage space)
1b. A re-evaluation of the minimum specifications for different node tiers could also help mitigate the amount of storage space
2. A re-evaluation of the fee charged to store files on ethoFS (unless the charges to upload are comparable to offerings from other hosting companies, ethoFS will have priced itself out of the market)
3. Promote the development of a DropBox type app that will allow the use ethoFS storage space for private, encrypted, P2P file sharing (users upload content, give it a password, then share the link/password with others to access it)
4. Encourage the development of a second method of storing websites (e.g. IPNS) as an option for users to rent storage space on the ethoFS network, which this will allow for dynamic content and easy updates. An IPNS option would be in addition to the IPFS system that is already in place, and the two file systems should work together depending on how the smart contract is executed, e.g. website is stored in IPNS space, but refers to static content that is stored in IPFS space
5. Create more video and audio (podcast) content to build awareness to the Ether-1 project and the phenomenal work that has already been accomplished (the project is beyond proof-of-concept, it's time to build use cases)
6. Coordinate with other team and community members to focus time, talent, and energy accordingly to bring about the aforementioned goals

**Comment by pistol22cal** [comment]
Contact Info:

Discord: @pistol22cal#7602 | Pistol of $ETHO since May'18 | ID: <378374529707278347>
email: admin@pistolcrypt.com

Ether-1 Community History
Hi, I am Pistol! I have been in the ETHO community since the beginning. 

Platform Summary
•	Focus on marketing
•	Develop our own mining algo and software
•	Decentralize Everything

Platform Details
We 1000% need to market what we have; we have a valid working product and supply a valuable service. People do not even know we exist, and I want to change this and now!
I want to be the voice for the little guy, the guy that has 1 GPU and wants to be a part of this whole thing we call crypto. I want ETHO to be the coin he wants to mine, and I want him to be profitable! I want node owners to be satisfied with their earnings and to be able to have a direct say in the direction that ETHO takes. Node owners are our investors, period, and as such should have a say in every aspect of the project’s development.
I believe we should develop our own mining algorithm and have our own miner software. It should be equally good on AMD and Nvidia. We should be ASIC resistant as well as FPGA resistant. This would be a big deal and allow us to move away from the crowd, allowing us to be minable on almost any modern GPU. DAG file size is an issue and if we can remove this limitation, we can have a nice future in mining.
I believe the monetary policy in its current form is fair to all and I would welcome changes if a fair and balanced policy could be achieved.
Rebranding is of little concern to me and I will not focus much effort into this area as I feel it is not a main concern currently. 
Finally, full decentralization is my focus for Ether-1 we need the tools Xerom is testing moved to Ether-1 ASAP once fully tested.

**Comment by Crypto-Saiyan** [comment]
Contact Info:

Discord: @Crypto_Saiyan of $ETHO Aug’18#9653
email: cryptosaiyan1@gmail.com

**Ether-1 Community History**:

I have been following Ether-1 since August 2018,mining,setting up Nodes,been part of the Community & helping where i can in Discord.
I believe in the idea of #DecentralizeEverything and I want to make it come true with Ether-1/Xerom.

**Platform Summary**:

• Focus on marketing
• Change Node Collateral
• Rebrand project to attract more people
• Realizing our goal to #DecentralizeEverything!

**Platform Details**:

We have a great working product & need to focus more on Marketing,get more Exposure.

I think we need to change the Node Collateral to get more Nodes Online on the network to help grow **ethoFS**.

Example:

**SN**: 5,000 ETHO
**MN**: 10,000 ETHO
**GN**:  20,000 ETHO

This way we would get more **Nodes** running with more space available for the **ethoFS** with no need to change the rewards while the **Node ROI** would be higher.

Monetary policy in its current state is fair to all & should remain as is.

Rebrand the project in order to move away from the name which is too similar to **Ethereum**,but it is not a main concern currently & should be done later on in 2020. 

Implementing **Decentralize Node Protocol** to ETHO Nodes once fully tested.

**Comment by Primate411** [comment]
Just a reminder that candidates should put in their info over at [https://github.com/Ether1Project/Governance/issues](https://github.com/Ether1Project/Governance/issues)

This thread is to discuss the specifics of how the management team (@Primate411 @Dev-JamesR @fallengravity and Treehouse) will work with the provisional council in order to setup the permanent council as described in the Medium post here: [https://medium.com/@Ether1Official/ether-1-governance-bootstrap-ee2689af8c63?source=---------3------------------](https://medium.com/@Ether1Official/ether-1-governance-bootstrap-ee2689af8c63?source=---------3------------------)

**Comment by Primate411** [comment]
The Ether-1 management team does not want to make decisions in a vacuum. Everyone who holds any $ETHO and who believes in fundamental decentralization should join this effort and make a real difference, not only for yourself but for people like you who will discover crypto during the next market cycle.

If you can't join with your existing name for whatever reason, you are free to participate incognito :wink: 

To us, crypto and decentralization is about participation, first and foremost.  You expect others to build you paradise and give you your freedoms, you will be waiting for a loooooooong time friends.

**Comment by Primate411** [comment]
Suggest extending the provisional council deadline to end of December to get more involvement. 👍 👎 

Everyone should reach out to folks who hold ETHO and who are into crypto for the tech & we will do the same. Democracy only works when we participate and crypto is a direct democracy kind of tech!

**Comment by Primate411** [comment]
After lengthy discussions in the [Ether-1 Discord](https://discord.gg/RBckYBY) it was decided that a deadline needs to be set for the formation of the Provisional Council.  

We need everyone to join the Discord and cast their vote in the #voting channel.  The vote will only be open until December 6th so act now!

Here are the options for setting a deadline for election of the Provisional Council:
- End of December
- End of January
- End of February

_In each of these cases, applicants will only be accepted until the 15th of the month, with the voting to elect the running participants taking the other half of the month._

**Comment by Primate411** [comment]
https://medium.com/@Ether1Official/provisional-council-election-logistics-responsibilities-and-dissolution-1bc35dbebed2

**Comment by Primate411** [comment]
The provisional leadership council has been elected.
