### ISSUE TITLE
Ether1 Project Spokesperson

### ISSUE THREAD

**Issue by hashratez** [Ether1Project/ECPs#10]
It is important for any efforts, projects, solutions, to have a consistent and unified message.  This avoids confusion to the greater world at large.  People need to relate to people.  Thus far Ether1 has not had any central point of contact in official capacity as such.  I believe that this has been detrimental to the project.  Having a "face behind Ether1" would be good.   

With that said, soon the Provisional Council (PC) will be announced.  I propose the new PC elects an Official Spokesperson to the project that can be used in all official messaging: Press Releases, Tweets, Social Network engagements, Announcements, Interviews etc.

Cost/Budget to this ECP is zero.

Please note I am not interested in being this person.

**Comment by Primate411** [comment]
@hashratez since you're suggesting centralizing a function in the project/ecosystem, I want to hear how you're going to square this away with decentralizing everything, which to me is the ultimate terminus and mission for the project.

An official spokesperson roles is problematic because suggests centralizing how the project looks around a single personality.  This is diametrically opposed with what we're trying to build: an ecosystem with democratic rules in place with no single person or entity in charge.  

Have you considered what happens if the project makes is big and this person is detained or otherwise messed with? The more I think about this idea, the less I like it I'm afraid. I will vote against any such position if elected to the council.

What I would be OK with hearing is how we will take this "Press Releases, Tweets, Social Network engagements, Announcements, Interviews etc." responsibility and distribute it across members of the council in a matter than ensures there are at least 2 people covering distributed communication channels.

**Comment by hashratez** [comment]
The spokesperson only articulates the wishes of the PC.  Don't confuse a consistent and professional message with some type of authoritative centralized personality.  It is bottom up.
