### ISSUE TITLE
ECP-3 Twitter Awareness Ad

### ISSUE THREAD

**Issue by pistol22cal** [Ether1Project/ECPs#15]
ECP-3: Ad Campaign on Twitter 60 days then reevaluate 
ECP Discussion End: 14 Feb 2020 0:00 UTC
ECP Vote Date Start | End: 15 Feb 2020 0:01 UTC to 18 Feb 2020 0:01 UTC
ECP Originator: Pistol22Cal
ECP Sponsor: Pistol22Cal
ECP Motivation: Ether-1 Awareness - Bring in people to the platform
ECP Summary: Budget for Twitter Ads

Details
https://business.twitter.com/en/help/campaign-setup/create-an-awareness-campaign.html

1.	$1 per day  -- Daily Maximum: this is the amount you want your campaign to spend per day. We’ll automatically stop showing your ads when this number is reached each day, and daily budgets reset each day at midnight. Daily Maximum is a required field for every campaign.
2.	https://business.twitter.com/en/help/campaign-editing-and-optimization/ad-groups.html
3.	Access to Ether-1 Twitter by a council member that knows how to run and setup ad’s 
4.	Payment Method - https://privacy.com/pricing - Suggest we use this or if someone would like to be reimbursed and pay for this with a personal account that would be fine too.
5.	Allotment from Dev. Fund of 5100 ETHO per month for this expense or Equivalent $30 USD per month in ETHO
6.	Who does what task can be discussed within the council and development team

**Comment by Primate411** [comment]
I think you're on to something here.  If someone patiently dedicates 60 days to fine turning a campaign on twitter we should get a lot of good community members and contributors from it.

I ran a simple $50 campaign a few months ago and it was starting to show some success but there was not enough time with only 2-3 days.  If someone carefully spends $10 a day on promoting the values of Ether-1 on twitter, this has a good chance to catch fire even with the right kind of twitter segment: #DecentralizeEverything aficionados. 

The lack of eye balls is hurting our market because people don't know what they don't know.  Providing awareness is part of a multi-pronged strategy to let the right people find out about us.  Some of the other parts of this strategy are: providing alternative options to get ETHO and creating solid use cases for www.ethoFS.com.

**Comment by pistol22cal** [comment]
Its a good chunk of the budget but imho twitter is where crypto is most welcomed and if it ends up not working we cancel the funding and dont reup the ECP. Awareness is critical imho.

**Comment by Bigpiggy01** [comment]
Have we looks at using something like coinkit for monetized tweets instead of traditional Twitter advertising? Might work out as better bang for buck.

**Comment by hashratez** [comment]
Guys, I think this is putting the cart before the horse.  Most important: What is the call to action?  If you run any marketing/ad campaign you need to ask the target audience to do something.  So we run a Twitter (or any other) campaign what are we asking them to do???? 
1. Visit our website?
2. Follow us on Twitter?
3. Join us on Discord?
4. Join us on Telegram?
5. Follow us on Reddit?
6. what are we asking????
PICK ONE--and ONLY ONE.
NEXT--when the take that action, the LANDING PAGE MUST BE THERE FOR THEM.  Sending them to our Homepage will be a total waste, it is so confusing.  We would need a specific landing page to convert them to the next action which is????
So to just blast "Twitter Awareness" IHMO without a specific call to action is a waste of money.  

CALL TO ACTION FIRST, then run the marketing effort.

My 2 cents...

**Comment by Bigpiggy01** [comment]
Makes perfect sense.
if we could get the price of ETH0FS hosting up on the main page on the ethofs site we would have something worth pushing.
Who doesn't like cheap hosting.

**Comment by pistol22cal** [comment]
Run the Twitter Ad to join discord simple as that

**Comment by pistol22cal** [comment]
Withdrawn
